/*
 * @Description:
 * @Author: Kenzi
 * @Date: 2021-04-14 10:43:18
 * @LastEditTime: 2021-04-14 15:15:11
 * @LastEditors: Kenzi
 */

const settingActionTypes = {
  GET_ALL_LANG_TYPE_START: "GET_ALL_LANG_TYPE_START",
  GET_ALL_LANG_TYPE_SUCCESS: "GET_ALL_LANG_TYPE_SUCCESS",
  GET_ALL_LANG_TYPE_FAILURE: "GET_ALL_LANG_TYPE_FAILURE",
  GET_LANG_TRANSLATIONS_START: "GET_LANG_TRANSLATIONS_START",
  GET_LANG_TRANSLATIONS_SUCCESS: "GET_LANG_TRANSLATIONS_SUCCESS",
  GET_LANG_TRANSLATIONS_FAILURE: "GET_LANG_TRANSLATIONS_FAILURE",
  CHANGE_LANG_START: "CHANGE_LANG_START",
  CHANGE_LANG_SUCCESS: "CHANGE_LANG_SUCCESS",
};

export default settingActionTypes;
