/*
 * @Description:
 * @Author: Kenzi
 * @Date: 2021-07-20 14:12:09
 * @LastEditTime: 2021-07-20 14:12:09
 * @LastEditors: Kenzi
 */

const notificationActionTypes = {
  ON_GET_NOTIFICATION_START: "ON_GET_NOTIFICATION_START",
  ON_GET_NOTIFICATION_SUCCESS: "ON_GET_NOTIFICATION_SUCCESS",
  ON_GET_NOTIFICATION_FAILURE: "ON_GET_NOTIFICATION_FAILURE",
  GOT_NEW_NOTIFICATION: "GOT_NEW_NOTIFICATION",
  UPDATE_NOTIFICATION: "UPDATE_NOTIFICATION",
  ON_REMOVE_NOTIFICATION: "ON_REMOVE_NOTIFICATION",
};

export default notificationActionTypes;
